Wg service overhaul (#36)
* dev update

still broken

* dev update 2

dude i am so burned out

* First successful build

did not want to lose this progress

* dev update

some DI and added delete confirm
TRANSACTION PAGE IS BROKEN:
MissingMethodException: Cannot dynamically create an instance of type 'BAR.Components.Pages.Transactions.TransactionHistory'. Reason: No parameterless constructor defined.

* Update TransactionHistory.razor

app does not connect to server and retries

* Update TransactionHistory.razor

* Update TransactionHistory.razor

breakpoint triggered in TransactionHistory.razor line 85

* dev update 3

* Update TransactionHistory.razor

* migration for new db

* Update TransactionHistory.razor

* User flow updates (#34) (#35)

* userflow changes and ui updates

wip, do not push.

* userflow updates

authentication required to access app pages.

working on offering the user to children of MainLayout pages, wip still. some things are broken, need to change oninitasync for children pages to prevent double interops.

do not merge.

* added redirect if authed

if user is logged in, will now redirect them instantly into the app from root.

working on fixing the cascading user param, not working atm.

* fixed budget page and MainLayout

Prior to this MainLayout and any page loaded by it would crash each other via concurrent await commands on the same object. now MainLayout guaranteed to finish first, then body pages follow.

* remove add transaction from sidebar

moved to header

Co-authored-by: max-dejesus <90429251+max-dejesus@users.noreply.github.com>

* Update TransactionHistory.razor

thank you max!

---------

Co-authored-by: max-dejesus <90429251+max-dejesus@users.noreply.github.com>